First week of Admin role
Dev-incubator/DIMS-Core.Triple-1 pull request #1
Opened 2022-01-31 16:17 UTC by Kondratovich

Added UserProfile and Direction tables, vUserProfile and vUserProgress views.
Created DeleteUser procedure.
Used Scaffold-DbContext to create a model based on existing database.
Implemented repositories for existing entities.

2022-02-04 17:44 UTC, PushMeNow requested changes

2022-02-04 17:44 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/DIMS-Core.Database.refactorlog
> +﻿<?xml version="1.0" encoding="utf-8"?>
Remove this file from PR

2022-02-04 17:44 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Tables/UserProfiles.sql
> +    [StartDate] DATE NULL,
Let make this field not nullable

2022-02-04 17:44 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Interfaces/IReadOnlyRepository.cs
> +        IQueryable<TEntity> GetAll();
I think that need to add GetById method because it is Read operation too.

2022-02-04 17:44 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Models/DIMSDatabaseContext.cs
> +        }
Remove it. You already have connection sting in config file.

2022-02-04 17:44 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/appsettings.json
> +    }
??

2022-02-04 17:44 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/Base/ReadOnlyRepository.cs
> +        protected ReadOnlyRepository(DbContext context)
You will get exception in DI if do not specify exect type of DbContext. Make it everywhere.

2022-02-05 07:48 UTC, Kondratovich commented on DIMS-Core.Database/DIMS-Core.Database/DIMS-Core.Database.refactorlog
> +﻿<?xml version="1.0" encoding="utf-8"?>
fixed

2022-02-05 07:48 UTC, Kondratovich commented on DIMS-Core.Database/DIMS-Core.Database/Tables/UserProfiles.sql
> +    [StartDate] DATE NULL,
fixed

2022-02-05 07:48 UTC, Kondratovich commented on DIMS-Core/DIMS-Core.DataAccessLayer/Interfaces/IReadOnlyRepository.cs
> +        IQueryable<TEntity> GetAll();
fixed

2022-02-05 07:49 UTC, Kondratovich commented on DIMS-Core/DIMS-Core.DataAccessLayer/Models/DIMSDatabaseContext.cs
> +        }
fixed

2022-02-05 07:49 UTC, Kondratovich commented on DIMS-Core/DIMS-Core/appsettings.json
> +    }
fixed

2022-02-06 13:58 UTC, PushMeNow requested changes

2022-02-06 13:58 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Models/DIMSDatabaseContext.cs
> +    public partial class DIMSDatabaseContext : DbContext
Wait why did you create separate context? Project already has context class for common DB you just have to rewrite it.

2022-02-06 14:36 UTC, kuzmiich approved these changes

2022-02-07 07:12 UTC, Kondratovich commented on DIMS-Core/DIMS-Core.DataAccessLayer/Models/DIMSDatabaseContext.cs
> +    public partial class DIMSDatabaseContext : DbContext
fixed

2022-02-07 18:09 UTC, PushMeNow approved these changes

2022-02-07 19:01 UTC, merged