First week of Member role
Dev-incubator/DIMS-Core.Triple-1 pull request #2
Opened 2022-02-01 14:51 UTC by DenisCo1100100

Added tables: UserTask, TaskTrack, TaskState;
Procedures: SetUserTaskAsFail, SetUserTaskAsSuccess;
View: vUserTask;

2022-02-04 17:50 UTC, PushMeNow requested changes

2022-02-04 17:50 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Tables/TaskState.sql
> +﻿CREATE TABLE [dbo].[TaskState]
Make all tables in plural form

2022-02-04 17:50 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Tables/TaskTrack.sql
> +	[UserTaskId] INT NOT NULL,
constaint?

2022-02-04 17:50 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Tables/UserTask.sql
> +	CONSTRAINT [FK_UserTask_TaskTrack] FOREIGN KEY ([TaskId]) REFERENCES [TaskTrack](TaskTrackId)
Wait what? How can you join UserTasks and TaskTracks tables?

2022-02-04 17:50 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/appsettings.json
> +  }
??

2022-02-05 16:56 UTC, DenisCo1100100 commented on DIMS-Core.Database/DIMS-Core.Database/Tables/TaskState.sql
> +﻿CREATE TABLE [dbo].[TaskState]
fixed

2022-02-05 16:57 UTC, DenisCo1100100 commented on DIMS-Core.Database/DIMS-Core.Database/Tables/TaskTrack.sql
> +	[UserTaskId] INT NOT NULL,
fixed

2022-02-05 16:57 UTC, DenisCo1100100 commented on DIMS-Core.Database/DIMS-Core.Database/Tables/UserTask.sql
> +	CONSTRAINT [FK_UserTask_TaskTrack] FOREIGN KEY ([TaskId]) REFERENCES [TaskTrack](TaskTrackId)
fixed

2022-02-05 16:57 UTC, DenisCo1100100 commented on DIMS-Core/DIMS-Core/appsettings.json
> +  }
fixed

2022-02-06 14:00 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Tables/UserTask.sql
> +	CONSTRAINT [FK_UserTask_TaskTrack] FOREIGN KEY ([TaskId]) REFERENCES [TaskTrack](TaskTrackId)
Still not fixed.

2022-02-06 14:00 UTC, PushMeNow requested changes

2022-02-06 14:00 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Tables/UserTasks.sql
> +	FOREIGN KEY([TaskId]) REFERENCES [dbo].[TaskTracks] ([TaskTrackId])
Still not fixed

2022-02-06 14:22 UTC, DenisCo1100100 commented on DIMS-Core.Database/DIMS-Core.Database/Tables/UserTasks.sql
> +	FOREIGN KEY([TaskId]) REFERENCES [dbo].[TaskTracks] ([TaskTrackId])
Fixed

2022-02-06 14:44 UTC, kuzmiich commented on DIMS-Core.Database/DIMS-Core.Database/Views/vUserTask.sql
> +		[TaskState] ON [UserTask].StateId = [TaskState].StateId
prettify this statement, pls.

2022-02-06 14:44 UTC, kuzmiich commented on DIMS-Core.Database/DIMS-Core.Database/Tables/TaskTracks.sql
> +	FOREIGN KEY([UserTaskId]) REFERENCES [dbo].[UserTasks]([UserTaskId])
Should you delete cascade UserTask?

2022-02-06 14:52 UTC, DenisCo1100100 commented on DIMS-Core.Database/DIMS-Core.Database/Tables/TaskTracks.sql
> +	FOREIGN KEY([UserTaskId]) REFERENCES [dbo].[UserTasks]([UserTaskId])
Fixed

2022-02-06 15:00 UTC, DenisCo1100100 commented on DIMS-Core.Database/DIMS-Core.Database/Views/vUserTask.sql
> +		[TaskState] ON [UserTask].StateId = [TaskState].StateId
Fixed

2022-02-06 17:34 UTC, kuzmiich approved these changes

2022-02-07 18:10 UTC, PushMeNow approved these changes

2022-02-07 19:16 UTC, merged