Add tables, views, procedures.
Dev-incubator/DIMS-Core.Triple-1 pull request #3
Opened 2022-02-04 19:38 UTC by creator-max

Added Tables: Tasks
Added Views: vTasks, vUserTrack
Added Procedures: DeleteTask

2022-02-07 18:15 UTC, PushMeNow requested changes

2022-02-07 18:15 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Views/vUserTrack.sql
> +﻿CREATE VIEW [dbo].[vUserTrack]
Table should be in plural form

2022-02-08 10:40 UTC, kuzmiich requested changes

2022-02-08 10:40 UTC, kuzmiich commented on DIMS-Core.Database/DIMS-Core.Database/Tables/Tasks.sql
> +	[Description]  NVARCHAR(255) NOT NULL,
The description should support NULL value on DB layer!

2022-02-08 17:06 UTC, kuzmiich approved these changes

2022-02-08 17:38 UTC, PushMeNow approved these changes

2022-02-08 17:46 UTC, merged